nodes:
- Cafeteria
- ChargingPoint
- Eingang
- Feuerloescher
- Frisoer
- Kapelle
- Konferenzraum
- Lift1
- Lift2
- Rezeption
- Station
- Teekueche
- WayPoint12
- WayPoint14
- WayPoint17
- WayPoint19
- WayPoint2
- WayPoint21
- WayPoint26
- WayPoint28
- WayPoint32
- WayPoint34
- WayPoint35
- WayPoint39
- WayPoint43
- WayPoint45
- WayPoint47
- WayPoint48
- WayPoint49
- WayPoint50
- WayPoint51
- WayPoint52
- WayPoint53
- WayPoint54
- WayPoint55
- WayPoint56
- WayPoint57
- WayPoint58
- WayPoint59
- WayPoint60
- WayPoint61
- WayPoint62
- WayPoint63
- WayPoint66
- WayPoint7
- WayPoint76
- WayPoint8
- WayPoint81
- WayPoint82
- WayPoint83
- WayPoint84
- WayPoint85
- WayPoint86
- WayPoint87
- WayPoint90
